### ISSUE TITLE
How to use in View?

### ISSUE THREAD

**Issue by geoidesic** [ADmad/cakephp-tree#4]
Hi ADmad,

I'm trying to get this helper working. I followed the installation instructions but I can't figure out how to use it in my templates. Please could you add instructions for this?

I tried the following:

1. Loaded the plugin to my AppView.php (none of these worked):
```
        $this->loadHelper('ADmad.Tree');
        $this->loadHelper('ADmad/Tree');
        $this->loadHelper('Tree');
```
2. Tried to use it in the Template:
I tried statically with:
```
use ADmad\Tree\View\Helper as Tree;
Tree::generate($myArrayOfData);
```
I tried dynamically with:
```
$this->Tree->generate($myArrayOfData);
```

Looking at the unit test I was confused... seems to be wrapping a view in Test, rather than loading it as a helper and also adding it as a behaviour to the model... I thought it was a view helper?

**Comment by ADmad** [comment]
Consult the Cake manual for how to load a plugin helper.

Then usage would be like:
```php
echo $this->Tree->generate($data);
```
